# Generated by Django 5.2.17 on 2026-08-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("country", models.CharField(default="India", max_length=80)),
                ("category", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("starting_price", models.PositiveIntegerField(default=0)),
                ("best_time", models.CharField(blank=True, max_length=120)),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("destination", models.CharField(max_length=120)),
                ("origin", models.CharField(blank=True, max_length=120)),
                ("days", models.PositiveIntegerField(default=3)),
                ("travelers", models.PositiveIntegerField(default=1)),
                ("budget", models.PositiveIntegerField(default=0)),
                ("interests", models.TextField(blank=True)),
                ("hotel_style", models.CharField(default="Budget", max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=180)),
                ("morning", models.TextField(blank=True)),
                ("afternoon", models.TextField(blank=True)),
                ("evening", models.TextField(blank=True)),
                ("estimated_cost", models.PositiveIntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_days",
                        to="travel.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
    ]
